name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build Docker image
      run: docker build -t ega2901_bot .

    - name: Log in to Docker Hub (if you're using Docker Hub)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image (if needed)
      run: docker push your_bot_image

    - name: Redeploy Docker container
      run: |
        docker-compose down
        docker-compose up -d
